/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package portfolio.cli.app


import portfolio.cli.app.credentials.LoginCredentialsLoader
import portfolio.cli.app.scraper.scraperIndex
import java.util.logging.Level
import java.util.logging.Logger


object App {
    const val appName = "Open-Source Investments Portfolio Kotlin CLI"
    const val version = "1.0.0"
//    const val debugMode = true
}

//const val ANSI_RED = "\u001B[31m"
//const val ANSI_GREEN = "\u001B[32m"

fun main(args: Array<String>) {
    Logger.getGlobal().level = Level.WARNING

    println("${App.appName}:: ${App.version}")

    val credentialsList = LoginCredentialsLoader.load();

    credentialsList.forEach { credentials ->
        val scraper = scraperIndex[credentials.scraper]

        scraper!!.start(credentials)

        if (scraper.rows.isEmpty()) {
            print("Could not find portfolio rows")
            return
        }

        println(" ")
        println(" ")
        println("Printing Portfolio")

        scraper.rows.forEach {

            if (it.plAmount == null || it.plAmount.toDoubleOrNull() == 0.0){
                println(it);
                return
            }

            println(it);

//            val plAmount = it.plAmount.toDouble()
//
//            if (plAmount > 0) {
//                println("$ANSI_GREEN $it")
//            } else if (plAmount < 0) {
//                println("$ANSI_RED $it")
//            }
        }
    }


}
