/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package portfolio.cli.app


import portfolio.cli.app.credentials.LoginCredentialsLoader
import portfolio.cli.app.scraper.scraperIndex
import java.util.concurrent.TimeUnit
import java.util.logging.Level
import java.util.logging.Logger


object App {
    const val appName = "Open-Source Investments Portfolio Kotlin CLI"
    const val version = "1.0.0"
//    const val debugMode = true
}


fun main(args: Array<String>) {
    Logger.getGlobal().level = Level.WARNING

    println("${App.appName}:: ${App.version}")

    val credentialsList = LoginCredentialsLoader.load();

    credentialsList.forEach { credentials ->
        val scraper = scraperIndex[credentials.scraper]

        scraper!!.start(credentials)

        if (scraper.rows.isEmpty()) {
            print("Could not find portfolio rows")
            return
        }


        PortfolioPrinter(scraper).print()

        while (true) {
            Thread.sleep(TimeUnit.MINUTES.toMillis(1))

            scraper.enterPortfolio()

            Thread.sleep(10000)

            scraper.readEntirePortfolio()

            PortfolioPrinter(scraper).print()
        }


    }


}
