# This is a basic workflow to help you get started with Actions

name: Build Workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: GIT Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8



      # Build all our Build Types at once ##
      - name: Build Artifacts
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: 6.5
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: portfolio-cli-app:packageDistribution

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: portfolio-kt-cli-bin
          path: |
            dist/
